### ISSUE TITLE
Gather and process November Invoice data

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#14]
- [x] combine data so you have the whole month
- [x] generate the csv
- [x] Wait for CSVs from OpenStack & Coldfront Storage
- [x] Run the non-billable cleanup
- [x] Provide CSV of cleaned data
- [x] Assuming it is not too much effort provide a non-billed csv as well.

**Comment by naved001** [comment]
invoices are here: https://drive.google.com/drive/folders/10jJ3SCInbttI8TjkJjmL5-k8RBYWKZH6
