### ISSUE TITLE
Automate Prometheus pull

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#15]
## Motivation
Currently, we pull Prometheus manually. We want to automate this.

## Completion Criteria
Data is saved from Prometheus.

## Description
- [ ] Automate
- [ ] test

## Completion dates
Desired - 2023-12-09
Required - 2023-12-21

**Comment by naved001** [comment]
I have the automation ready using tekton pipelines, but haven't decided on a place where to host that for that reason I will keep this open.

https://github.com/naved001/tekton-playground/blob/main/metrics-collect.yaml

**Comment by naved001** [comment]
I need to handle the scenario when the metric pull fails due to DNS failures. Just noting it down here

**Comment by joachimweyl** [comment]
What are the next steps to resolve this pull failure?

**Comment by naved001** [comment]
> What are the next steps to resolve this pull failure?

I will create a PR soon to handle network failures.

**Comment by naved001** [comment]
I have a kubernetes cronjob on nerc-prod cluster that runs once a day and uploads the metrics to our b2 bucket.

For backup, I also have a regular cronjob running on an ovirt VM (ubuntu@172.16.0.234) that collects the metrics locally (i.e. not uploaded to B2).
