### ISSUE TITLE
Add Pulling Institution - Specific Code from ColdFront to OpenShift Invoice Script

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#28]
## Motivation
We need to gather the `Institution - Specific Code` from ColdFront no that it is being tracked by Harvard. 

## Completion Criteria
`Institution - Specific Code` added to invoice csv export. Harvard currently will be the only institution with this filled.

## Description
- [x] Reach out to @knikolla to see how he is pulling from ColdFront in his OpenShift Invoice Script
- [x] Update Invoice script
- [x] Confirm `Institution - Specific Code` has been added to ColdFront [here](https://github.com/nerc-project/operations/issues/223)
- [ ] Test to make sure Harvard has some data filled out

## Completion dates
Desired - 2024-01-29
Required - 2024-10-31

**Comment by naved001** [comment]
This is mostly done, but I haven't updated the tests. Here's the work that I did on this: https://github.com/CCI-MOC/openshift-usage-scripts/compare/main...naved001:openshift-usage-scripts:use-coldfront

**Comment by naved001** [comment]
https://github.com/CCI-MOC/openshift-usage-scripts/pull/36 now adds this information to the csv generated for openshift invoice. Although the field isn't actually populated yet. I had tested pulling this when Milson had briefly added this field. @joachimweyl can we close this issue then?

**Comment by joachimweyl** [comment]
If this means that the test worked when Milson briefly added this field then yes.
