### ISSUE TITLE
Gather and process February Invoice data

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#35]
## Motivation
Create Invoice data CSV from the OpenShift, OpenStack, and ColdFront Storage data.

## Completion Criteria
CSV was created with all 3 sets of data represented.

## Description
- [x] Combine data so you have the whole month
- [x] Generate the CSV
- [x] Wait for CSVs from OpenStack & Coldfront Storage
- [x] Run the non-billable cleanup
- [x] Provide CSV of cleaned data
- [x] Provide a non-billed CSV as well.

## Completion dates
Desired - 2024-03-01
Required - 2024-03-02

**Comment by naved001** [comment]
uploaded to google drive
