### ISSUE TITLE
Add new Lenovo GPU flavor to OpenShift Invoice Script

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#48]
## Motivation
We have new loaner GPUs from Lenovo we need to account for. The new pricing will be $2.078.

## Completion Criteria
New flavor calculated properly by invoice script

## Description
- [ ] If [this](https://github.com/nerc-project/operations/issues/420) is done update the repo else
- [ ] add new SU to the script calculation
   - "OpenShift GPUA100SXM4", 1 GPU, 32 vCPU, 245 GB RAM
- [ ] SU applies to all SUs that use wrk-91-100

## Completion dates
Desired - 2024-03-27
Required - TBD

**Comment by naved001** [comment]
this GPU is now supported.
